import { z } from "zod";

export const PlatformSchema = z.enum(["tomato", "feilu", "qidian", "other"]);
export type Platform = z.infer<typeof PlatformSchema>;

export const GenreSchema = z.enum([
  "xuanhuan",
  "xianxia",
  "urban",
  "horror",
  "rebirth",
  "system",
  "onlinegame",
  "apocalypse",
  "interstellar",
  "infinite",
  "strange-rules",
  "lord",
  "management",
  "family",
  "court-politics",
  "entertainment",
  "simulator",
  "checkin",
  "cyberpunk",
  "harem-household",
  "detective",
  "tycoon",
  "multiverse",
  "mastermind",
  "identities",
  "medical",
  "esports",
  "folklore",
  "mecha",
  "son-in-law",
  "treasure",
  "conquest",
  "construction",
  "arranged-love",
  "chasing-love",
  "parenting",
  "workplace",
  "quick-transmigration",
  "period-life",
  "showbiz",
  "female-mystery",
  "healing",
  "locked-room",
  "cthulhu",
  "survival-horror",
  "campus-horror",
  "livestream-horror",
  "time-loop",
  "ai-awakening",
  "first-contact",
  "space-colony",
  "hard-sf",
  "wasteland",
  "espionage",
  "bureaucracy",
  "business-war",
  "legal",
  "archaeology",
  "travel-adventure",
  "sports",
  "other",
]);
export type Genre = z.infer<typeof GenreSchema>;

export const BookStatusSchema = z.enum([
  "incubating",
  "outlining",
  "active",
  "paused",
  "completed",
  "dropped",
]);
export type BookStatus = z.infer<typeof BookStatusSchema>;

export const BookConfigSchema = z.object({
  id: z.string().min(1),
  title: z.string().min(1),
  platform: PlatformSchema,
  genre: GenreSchema,
  status: BookStatusSchema,
  targetChapters: z.number().int().min(1).default(200),
  chapterWordCount: z.number().int().min(1000).default(3000),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
});

export type BookConfig = z.infer<typeof BookConfigSchema>;
